# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fca31d723d5758067cdfd3edcb88842a31826b7f11408b71efcb6a4bdd83aee4494fd0de2cfc30f481a302f6130c9d7241e070a3103abda9a20bb87ab53f204e

test:
  secret_key_base: 15beb241a45dbf5f4ab4cf72fea4a207d7866d09ff2ab695c34cc78bec85d18310f7746a7a57f9112c1c751d69caa23f6185545e4b72f1456783783fb0fcde63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
